databases:
  - name: ruadis_db
    databaseName: ruadis_db
    user: delegado
    password: admin123

 services:
 - type: pserv
   name: pgbouncer
   env: docker
   plan: starter plus
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: DATABASE_URL
     fromDatabase:
       name: ruadis_db
       property: postgres://delegado:admin123@localhost:5432/ruadis_db
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50
