databases:
  - name: ruadis_db
    databaseName: ruadis_db
    user: delegado

services:
  - type: web
    name: blitzapp
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false &&
      blitz prisma generate &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start -p ${PORT}
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ruadis_db
          property: postgres://delegado:admin123@localhost:5432/ruadis_db
      - key: SESSION_SECRET_KEY
        generateValue: true
        - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50
